const provinces = [
    { eng: 'Badakhshan', pashto: 'بدخشان' },
    { eng: 'Badghis', pashto: 'بدخشان' },
    { eng: 'Baghlan', pashto: 'بغلان' },
    { eng: 'Balkh', pashto: 'بلخ' },
    { eng: 'Bamyan', pashto: 'بامیان' },
    { eng: 'Daykundi', pashto: 'دایکندی' },
    { eng: 'Farah', pashto: 'فراه' },
    { eng: 'Faryab', pashto: 'فاریاب' },
    { eng: 'Ghazni', pashto: 'غزنی' },
    { eng: 'Ghor', pashto: 'غور' },
    { eng: 'Helmand', pashto: 'هلمند' },
    { eng: 'Herat', pashto: 'هرات' },
    { eng: 'Jowzjan', pashto: 'جوزجان' },
    { eng: 'Kabul', pashto: 'کابل' },
    { eng: 'Kandahar', pashto: 'کندهار' },
    { eng: 'Kapisa', pashto: 'کاپیسا' },
    { eng: 'Khost', pashto: 'خوست' },
    { eng: 'Kunar', pashto: 'کونړ' },
    { eng: 'Kunduz', pashto: 'کندز' },
    { eng: 'Laghman', pashto: 'لغمان' },
    { eng: 'Logar', pashto: 'لوگر' },
    { eng: 'Nangarhar', pashto: 'ننګرهار' },
    { eng: 'Nimroz', pashto: 'نمروز' },
    { eng: 'Nuristan', pashto: 'نورستان' },
    { eng: 'Paktia', pashto: 'پکتیا' },
    { eng: 'Paktika', pashto: 'پکتیکا' },
    { eng: 'Panjshir', pashto: 'پنجشیر' },
    { eng: 'Parwan', pashto: 'پروان' },
    { eng: 'Samangan', pashto: 'سمنګان' },
    { eng: 'Sar-e-Pol', pashto: 'سرپل' },
    { eng: 'Takhar', pashto: 'تخار' },
    { eng: 'Urozgan', pashto: 'اورزګان' },
    { eng: 'Wardak', pashto: 'وردګ' },
    { eng: 'Zabul', pashto: 'زابل' }
  ];
export default provinces;  